name: CMake

on:
  push:
    branches: ["main"]
    paths:
      - "ports/cpp/**"
      - ".github/workflows/cmake.yml"
      - "tests/*.g4"
  pull_request:
    branches: ["main"]
    paths:
      - "ports/cpp/**"
      - ".github/workflows/cmake.yml"
      - "tests/*.g4"

jobs:
  build:
    strategy:
      matrix:
        cmake_build_type: [Asan, Release]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          wget -O - https://apt.llvm.org/llvm-snapshot.gpg.key | sudo apt-key add -
          sudo add-apt-repository "deb http://apt.llvm.org/noble/ llvm-toolchain-noble-18 main"
          sudo apt update
          sudo apt install build-essential
          sudo apt install clang-format-18 clang-tidy-18
          pip install conan

      - name: Setup ccache
        uses: hendrikmuhs/ccache-action@v1.2
        with:
          create-symlink: true
          key: ${{ github.job }}-${{ matrix.cmake_build_type }}

      - name: Clang-Format
        working-directory: ${{github.workspace}}/ports/cpp
        run: sh ./ci/check-format.sh

      - name: Configure
        working-directory: ${{github.workspace}}/ports/cpp
        run: |
          conan profile detect

          conan install . \
            --output-folder=build \
            --build=missing \
            --settings=build_type=${{ matrix.cmake_build_type }}

          cd build
          cmake \
            -DANTLR4C3_DEVELOPER=ON \
            -DCMAKE_BUILD_TYPE=${{ matrix.cmake_build_type }} \
            ..

      - name: Build
        working-directory: ${{github.workspace}}/ports/cpp/build
        run: make

      - name: Unit Test
        working-directory: ${{github.workspace}}/ports/cpp
        run: sh ./ci/test.sh

      - name: Clang-Tidy on sources
        if: matrix.cmake_build_type == 'Release'
        working-directory: ${{github.workspace}}/ports/cpp
        run: sh ./ci/check-style.sh
