name: Dart

on:
  push:
    branches: ["main"]
    paths:
      - "ports/dart/**"
      - ".github/workflows/dart.yml"
  pull_request:
    branches: ["main"]
    paths:
      - "ports/dart/**"
      - ".github/workflows/dart.yml"

jobs:
  build:
    runs-on: dart
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Test
        working-directory: ${{github.workspace}}/ports/dart
        run: dart test
